# Generated by Django 2.2.4 on 2019-09-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('votes_total',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('vehicles', 'vehicles'), ('phones', 'phones')], null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
